# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: main.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'main.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmain.proto\"6\n\x0bHideRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x18\n\x10secret_encrypted\x18\x02 \x01(\x0c\"2\n\x0cHideResponse\x12\x13\n\x0bstego_image\x18\x01 \x01(\x0c\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"%\n\x0e\x45xtractRequest\x12\x13\n\x0bstego_image\x18\x01 \x01(\x0c\":\n\x0f\x45xtractResponse\x12\x18\n\x10secret_decrypted\x18\x01 \x01(\x0c\x12\r\n\x05\x65rror\x18\x02 \x01(\t2i\n\x14SteganographyService\x12#\n\x04Hide\x12\x0c.HideRequest\x1a\r.HideResponse\x12,\n\x07\x45xtract\x12\x0f.ExtractRequest\x1a\x10.ExtractResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'main_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HIDEREQUEST']._serialized_start=14
  _globals['_HIDEREQUEST']._serialized_end=68
  _globals['_HIDERESPONSE']._serialized_start=70
  _globals['_HIDERESPONSE']._serialized_end=120
  _globals['_EXTRACTREQUEST']._serialized_start=122
  _globals['_EXTRACTREQUEST']._serialized_end=159
  _globals['_EXTRACTRESPONSE']._serialized_start=161
  _globals['_EXTRACTRESPONSE']._serialized_end=219
  _globals['_STEGANOGRAPHYSERVICE']._serialized_start=221
  _globals['_STEGANOGRAPHYSERVICE']._serialized_end=326
# @@protoc_insertion_point(module_scope)
